#Modo de simulacion. true para modo simulacion y false para modo real
simulation_mode: true 

#Longitud de la herramienta respecto del EF
tool_length: 0.1275

#Orientacion de la herramienta respecto del EF
tool_orientation: [0.0, 0.0, 0.0] 

#Punto de fulcro. Debe estar entre 0 y 1. Indica en que punto de la longitud de la herramienta esta el punto de fulcro
fulcrum_fi: 0.5 

#ip del robot
robot_ip: "" 

#Modo de trabajo."pivot" si está en modo pivotaje alrededor del punto de fulcro y "free" para modo libre 
work_mode: "pivot" 
